name: tagpr

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'feature/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}