name: tagpr

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'feature/')
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - uses: Songmu/tagpr@75738aa2880a03a1036bc5bd90ef49853427ec65 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}